"""
Reset ALL vitals history and reseed it with a curated demonstration dataset
for the demo patient (Yussif Hamza, hamza@rpm.com / PatientPass123).

The readings tell a staged clinical story so the kept file + app show the
FULL risk range:
  Phase 1  LOW      - weeks of normal vitals (diabetes/hypertension LOW)
  Phase 2  MODERATE - glucose & BP drift upward
  Phase 3  HIGH     - sustained elevated glucose/pressure
  Phase 4  CRITICAL - severe readings, sustained
  Phase 5  RECOVERY - post-intervention improvement back to MODERATE

Each reading goes through the REAL pipeline (VitalsService.record_reading),
so predictions, reasons, recommendations, alerts and notifications are all
authentically generated by the same code the running app uses.

Output files written to <repo>/demo-data/:
  demo_vitals_history.csv  - chronological table with per-condition risk
  demo_vitals_history.md   - presentation-ready summary
"""

import sys, os
sys.path.insert(0, ".")
os.environ.setdefault("ENVIRONMENT", "development")

import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

from app.db.session import SessionLocal
from app.models.patient import PatientProfile
from app.models.vitals import VitalReading
from app.models.prediction import RiskPrediction
from app.models.alert import Alert
from app.models.notification import Notification
from app.models.enums import DiseaseType, RiskLevel, VitalSource
from app.schemas.vitals import VitalReadingCreate
from app.services.vitals_service import VitalsService

STROKE, DIABETES, HYPERTENSION = DiseaseType.STROKE, DiseaseType.DIABETES, DiseaseType.HYPERTENSION
ALL_CONDITIONS = [DIABETES, HYPERTENSION, STROKE]

# (days_ago, source, sys, dia, hr, glucose, pedigree, bmi, spo2, temp, rr, weight, note)
READINGS = [
    (56, "manual", 112, 74, 60, 100.0, 0.28, 24.4, 98.0, 36.3, 15, 70.5, "Routine check-in, feeling well."),
    (53, "manual", 114, 75, 62, 104.0, 0.30, 24.5, 98.0, 36.4, 15, 70.8, "Baseline vitals normal."),
    (50, "manual", 116, 76, 63, 108.0, 0.32, 24.6, 98.0, 36.4, 15, 71.0, "No complaints."),
    (46, "manual", 128, 81, 68, 128.0, 0.42, 25.2, 97.0, 36.5, 16, 72.6, "Slightly elevated glucose after heavy meal."),
    (42, "manual", 130, 82, 69, 133.0, 0.45, 25.4, 97.0, 36.5, 16, 73.0, "Watching diet, fewer sweets."),
    (38, "manual", 132, 84, 71, 138.0, 0.48, 25.6, 97.0, 36.6, 16, 73.5, "Blood pressure starting to trend up."),
    (34, "manual", 135, 85, 72, 142.0, 0.50, 25.8, 96.0, 36.6, 16, 73.9, "Pre-hypertensive range noted."),
    (30, "manual", 138, 88, 74, 146.0, 0.55, 26.0, 96.0, 36.7, 17, 74.4, "Moderate risk, lifestyle counselling started."),
    (26, "manual", 148, 92, 78, 188.0, 0.65, 26.4, 95.0, 36.8, 17, 75.4, "Consistently elevated pressure and glucose."),
    (22, "manual", 150, 93, 79, 192.0, 0.67, 26.5, 95.0, 36.8, 17, 75.8, "High risk, medication review suggested."),
    (18, "manual", 152, 94, 80, 196.0, 0.68, 26.6, 95.0, 36.9, 18, 76.1, "Marked worsening since last check-in."),
    (14, "manual", 156, 96, 82, 204.0, 0.70, 26.8, 94.0, 36.9, 18, 76.7, "Uncontrolled readings, advised to seek care."),
    (10, "manual", 172, 106, 90, 242.0, 0.84, 27.4, 93.0, 37.1, 19, 78.0, "CRITICAL — hospital review advised."),
    (9,  "manual", 176, 108, 92, 250.0, 0.86, 27.5, 92.0, 37.2, 19, 78.3, "CRITICAL sustained — emergency protocol."),
    (8,  "manual", 150, 94, 80, 178.0, 0.68, 26.9, 95.0, 37.0, 18, 76.9, "Post-clinic review, treatment started."),
    (6,  "manual", 142, 89, 75, 155.0, 0.60, 26.4, 96.0, 36.9, 17, 75.9, "Improving on medication."),
    (4,  "manual", 138, 87, 73, 148.0, 0.55, 26.1, 96.0, 36.8, 17, 75.3, "Better control, staying on plan."),
    (2,  "manual", 134, 85, 71, 142.0, 0.52, 25.9, 97.0, 36.7, 16, 74.8, "Stable — moderate risk, monitoring continues."),
]

SRC = {s.value if hasattr(s, "value") else s: VitalSource(s) for s in [VitalSource.MANUAL, VitalSource.DEVICE, VitalSource.CLINIC]}


def risk_cell(level: RiskLevel, score: float) -> str:
    return f"{level.value} ({score:.3f})"


def main():
    repo_root = Path(__file__).resolve().parent.parent
    out_dir = repo_root / "demo-data"
    out_dir.mkdir(exist_ok=True)

    db = SessionLocal()
    try:
        patients = db.query(PatientProfile).all()
        if not patients:
            print("No patient profiles found — nothing to do.")
            return
        for p in patients:
            db.query(Notification).filter(Notification.user_id == p.user_id).delete(synchronize_session=False)
            db.query(Alert).filter(Alert.patient_id == p.id).delete(synchronize_session=False)
            db.query(RiskPrediction).filter(RiskPrediction.patient_id == p.id).delete(synchronize_session=False)
            db.query(VitalReading).filter(VitalReading.patient_id == p.id).delete(synchronize_session=False)
        db.commit()

        svc = VitalsService(db)
        now = datetime.now(timezone.utc)

        rows = []
        for (days_ago, source, sys_, dia, hr, glu, ped, bmi, spo2, temp, rr, weight, note) in READINGS:
            result = svc.record_reading(
                patients[0].id,
                VitalReadingCreate(
                    recorded_at=now - timedelta(days=days_ago),
                    source=SRC[source],
                    conditions=ALL_CONDITIONS,
                    blood_pressure_systolic=sys_,
                    blood_pressure_diastolic=dia,
                    heart_rate_bpm=hr,
                    blood_glucose_mg_dl=glu,
                    diabetes_pedigree_function=ped,
                    bmi=bmi,
                    spo2_percent=spo2,
                    temperature_celsius=temp,
                    respiratory_rate=rr,
                    weight_kg=weight,
                    notes=note,
                ),
            )
            preds = {p.disease_type: p for p in result.predictions}
            rows.append(
                {
                    "recorded_at": result.vital.recorded_at,
                    "source": result.vital.source.value,
                    "sys": sys_, "dia": dia, "hr": hr, "glu": glu,
                    "bmi": bmi, "spo2": spo2, "temp": temp, "rr": rr, "weight": weight,
                    "notes": note,
                    "diabetes": preds.get(DIABETES),
                    "hypertension": preds.get(HYPERTENSION),
                    "stroke": preds.get(STROKE),
                }
            )
            lvl = lambda p: p.risk_level.value if p else "-"
            print(f"  {result.vital.recorded_at.strftime('%Y-%m-%d')}  sys {sys_:>3} glu {glu:>5.1f}  "
                  f"diab {lvl(preds.get(DIABETES)):>8} hype {lvl(preds.get(HYPERTENSION)):>8} stroke {lvl(preds.get(STROKE)):>8}")

        # --- Write the kept files -----------------------------------------------------------------
        csv_path = out_dir / "demo_vitals_history.csv"
        with open(csv_path, "w", newline="", encoding="utf-8-sig") as f:
            import csv as _csv
            w = _csv.writer(f)
            w.writerow([
                "Date & Time", "Source", "Systolic BP (mmHg)", "Diastolic BP (mmHg)",
                "Heart Rate (bpm)", "Blood Glucose (mg/dL)", "BMI", "SpO2 (%)",
                "Temp (C)", "Resp Rate", "Weight (kg)",
                "Diabetes Risk", "Hypertension Risk", "Stroke Risk", "Notes",
            ])
            for r in rows:
                w.writerow([
                    r["recorded_at"].strftime("%Y-%m-%d %H:%M"),
                    r["source"], r["sys"], r["dia"], r["hr"], r["glu"], r["bmi"],
                    r["spo2"], r["temp"], r["rr"], r["weight"],
                    risk_cell(r["diabetes"].risk_level, r["diabetes"].risk_score) if r["diabetes"] else "-",
                    risk_cell(r["hypertension"].risk_level, r["hypertension"].risk_score) if r["hypertension"] else "-",
                    risk_cell(r["stroke"].risk_level, r["stroke"].risk_score) if r["stroke"] else "-",
                    r["notes"],
                ])

        md_path = out_dir / "demo_vitals_history.md"
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(f"# Demo Vitals History — Yussif Hamza\n\n")
            f.write(f"Patient: Yussif Hamza (male, 56) | Primary condition: Stroke\n")
            f.write(f"Total readings: {len(rows)} | Period: {rows[-1]['recorded_at'].strftime('%Y-%m-%d')} → {rows[0]['recorded_at'].strftime('%Y-%m-%d')}\n\n")
            f.write("## Risk story\n\n")
            f.write("| Phase | Reading(s) | Vitals pattern | Diabetes | Hypertension | Stroke |\n")
            f.write("|---|---|---|---|---|---|---|\n")
            f.write("| **1 — Low** | 1–3 | Normal BP/glucose, weight stable | LOW | LOW | HIGH (chronic profile) |\n")
            f.write("| **2 — Moderate** | 4–8 | Glucose 128→146, BP 128/81→138/88, BMI 25.2→26.0 | LOW→MODERATE | MODERATE | HIGH |\n")
            f.write("| **3 — High** | 9–12 | Sustained BP ≥148/92, glucose 188→204 | HIGH | CRITICAL | CRITICAL |\n")
            f.write("| **4 — Critical** | 13–14 | Severe 176/108, glucose 250, HR 92 | CRITICAL | CRITICAL | CRITICAL |\n")
            f.write("| **5 — Recovery** | 15–18 | Post-intervention: BP/glucose fall, weight drops | HIGH→MODERATE | MODERATE | HIGH |\n\n")
            f.write("## Readings\n\n")
            f.write("| Date & Time | Source | Systolic | Diastolic | HR | Glucose | BMI | SpO2 | Weight | Diabetes | Hypertension | Stroke | Notes |\n")
            f.write("|---|---|---|---|---|---|---|---|---|---|---|---|---|\n")
            for r in rows:
                f.write(
                    f"| {r['recorded_at'].strftime('%Y-%m-%d %H:%M')} | {r['source']} "
                    f"| {r['sys']} | {r['dia']} | {r['hr']} | {r['glu']:.0f} | {r['bmi']:.1f} | {r['spo2']:.0f} | {r['weight']:.1f} "
                    f"| {risk_cell(r['diabetes'].risk_level, r['diabetes'].risk_score) if r['diabetes'] else '-'} "
                    f"| {risk_cell(r['hypertension'].risk_level, r['hypertension'].risk_score) if r['hypertension'] else '-'} "
                    f"| {risk_cell(r['stroke'].risk_level, r['stroke'].risk_score) if r['stroke'] else '-'} "
                    f"| {r['notes']} |\n"
                )

        print(f"\nWrote {csv_path}")
        print(f"Wrote {md_path}")
        print(f"Readings: {len(rows)} | Predictions: {db.query(RiskPrediction).count()}")
    finally:
        db.close()


if __name__ == "__main__":
    main()