"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-18

Hand-written (not autogenerated) initial migration creating all 13 tables
defined in app/models/*.py. Tables are created in FK-dependency order;
downgrade() drops them in reverse order and then drops the Postgres ENUM
types explicitly (Postgres does not drop a custom ENUM type automatically
just because the table using it was dropped).

If you add/change a model after this migration exists, do NOT edit this
file — generate a new one:
    alembic revision --autogenerate -m "describe the change"
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- users ---
    op.create_table(
        "users",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(150), nullable=False),
        sa.Column("phone_number", sa.String(20), nullable=True),
        sa.Column(
            "role",
            sa.Enum("admin", "doctor", "patient", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("is_verified", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_users_email", "users", ["email"])
    op.create_index("ix_users_role", "users", ["role"])

    # --- admin_profiles ---
    op.create_table(
        "admin_profiles",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "user_id",
            sa.String(36),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("department", sa.String(150), nullable=True),
        sa.Column("job_title", sa.String(150), nullable=True),
        sa.Column("is_super_admin", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("permissions", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    # --- doctor_profiles ---
    op.create_table(
        "doctor_profiles",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "user_id",
            sa.String(36),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column("specialization", sa.String(150), nullable=False),
        sa.Column("license_number", sa.String(100), nullable=False, unique=True),
        sa.Column("years_of_experience", sa.Integer, nullable=True),
        sa.Column("hospital_affiliation", sa.String(200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    # --- patient_profiles ---
    op.create_table(
        "patient_profiles",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "user_id",
            sa.String(36),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "assigned_doctor_id",
            sa.String(36),
            sa.ForeignKey("doctor_profiles.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("date_of_birth", sa.Date, nullable=False),
        sa.Column("gender", sa.Enum("male", "female", "other", name="gender"), nullable=False),
        sa.Column("blood_group", sa.String(5), nullable=True),
        sa.Column("height_cm", sa.Float, nullable=True),
        sa.Column("weight_kg", sa.Float, nullable=True),
        sa.Column("emergency_contact_name", sa.String(150), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(20), nullable=True),
        sa.Column("chronic_conditions_summary", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    # --- vital_readings ---
    op.create_table(
        "vital_readings",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "patient_id",
            sa.String(36),
            sa.ForeignKey("patient_profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum("manual", "device", "clinic", name="vital_source"),
            nullable=False,
            server_default="manual",
        ),
        sa.Column("blood_pressure_systolic", sa.Integer, nullable=True),
        sa.Column("blood_pressure_diastolic", sa.Integer, nullable=True),
        sa.Column("heart_rate_bpm", sa.Integer, nullable=True),
        sa.Column("blood_glucose_mg_dl", sa.Float, nullable=True),
        sa.Column("spo2_percent", sa.Float, nullable=True),
        sa.Column("temperature_celsius", sa.Float, nullable=True),
        sa.Column("respiratory_rate", sa.Integer, nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_vitals_patient_recorded", "vital_readings", ["patient_id", "recorded_at"])

    # --- risk_predictions ---
    op.create_table(
        "risk_predictions",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "patient_id",
            sa.String(36),
            sa.ForeignKey("patient_profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "source_vital_id",
            sa.String(36),
            sa.ForeignKey("vital_readings.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "disease_type",
            sa.Enum("stroke", "diabetes", "hypertension", name="disease_type"),
            nullable=False,
        ),
        sa.Column("risk_score", sa.Float, nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum("low", "moderate", "high", "critical", name="risk_level"),
            nullable=False,
        ),
        sa.Column("model_version", sa.String(50), nullable=False),
        sa.Column("input_features", sa.JSON(), nullable=False),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_risk_predictions_disease_type", "risk_predictions", ["disease_type"])

    # --- alerts ---
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "patient_id",
            sa.String(36),
            sa.ForeignKey("patient_profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "doctor_id",
            sa.String(36),
            sa.ForeignKey("doctor_profiles.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "related_vital_id",
            sa.String(36),
            sa.ForeignKey("vital_readings.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "related_prediction_id",
            sa.String(36),
            sa.ForeignKey("risk_predictions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("message", sa.Text, nullable=False),
        sa.Column(
            "severity",
            sa.Enum("info", "warning", "critical", name="alert_severity"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("new", "acknowledged", "resolved", name="alert_status"),
            nullable=False,
            server_default="new",
        ),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_alerts_severity", "alerts", ["severity"])
    op.create_index("ix_alerts_status", "alerts", ["status"])

    # --- medications ---
    op.create_table(
        "medications",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "patient_id",
            sa.String(36),
            sa.ForeignKey("patient_profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "prescribed_by_id",
            sa.String(36),
            sa.ForeignKey("doctor_profiles.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("dosage", sa.String(100), nullable=False),
        sa.Column("frequency", sa.String(100), nullable=False),
        sa.Column("instructions", sa.Text, nullable=True),
        sa.Column("start_date", sa.Date, nullable=False),
        sa.Column("end_date", sa.Date, nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    # --- medication_logs ---
    op.create_table(
        "medication_logs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "medication_id",
            sa.String(36),
            sa.ForeignKey("medications.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("taken", "missed", "skipped", name="medication_status"),
            nullable=False,
        ),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    # --- appointments ---
    op.create_table(
        "appointments",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "patient_id",
            sa.String(36),
            sa.ForeignKey("patient_profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "doctor_id",
            sa.String(36),
            sa.ForeignKey("doctor_profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer, nullable=False, server_default="30"),
        sa.Column("reason", sa.String(255), nullable=False),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column(
            "status",
            sa.Enum("scheduled", "completed", "cancelled", "no_show", name="appointment_status"),
            nullable=False,
            server_default="scheduled",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_appointments_scheduled_at", "appointments", ["scheduled_at"])
    op.create_index("ix_appointments_status", "appointments", ["status"])

    # --- medical_history_entries ---
    op.create_table(
        "medical_history_entries",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "patient_id",
            sa.String(36),
            sa.ForeignKey("patient_profiles.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("condition_name", sa.String(200), nullable=False),
        sa.Column("diagnosed_date", sa.Date, nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        sa.Column("recorded_by", sa.String(150), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    # --- notifications ---
    op.create_table(
        "notifications",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "user_id",
            sa.String(36),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("message", sa.Text, nullable=False),
        sa.Column("notification_type", sa.String(50), nullable=False),
        sa.Column("is_read", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    # --- audit_logs (no updated_at — insert-only by design) ---
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column(
            "user_id",
            sa.String(36),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("entity_type", sa.String(100), nullable=False),
        sa.Column("entity_id", sa.String(100), nullable=True),
        sa.Column("ip_address", sa.String(45), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"])
    op.create_index("ix_audit_logs_entity_type", "audit_logs", ["entity_type"])


def downgrade() -> None:
    # Drop in reverse FK-dependency order.
    op.drop_table("audit_logs")
    op.drop_table("notifications")
    op.drop_table("medical_history_entries")
    op.drop_table("appointments")
    op.drop_table("medication_logs")
    op.drop_table("medications")
    op.drop_table("alerts")
    op.drop_table("risk_predictions")
    op.drop_table("vital_readings")
    op.drop_table("patient_profiles")
    op.drop_table("doctor_profiles")
    op.drop_table("admin_profiles")
    op.drop_table("users")

    # Postgres ENUM types are NOT dropped automatically when the table
    # using them is dropped — drop them explicitly or they'll silently
    # persist and collide if this migration is ever re-run.
    bind = op.get_bind()
    for enum_name in (
        "user_role",
        "gender",
        "vital_source",
        "disease_type",
        "risk_level",
        "alert_severity",
        "alert_status",
        "medication_status",
        "appointment_status",
    ):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
